### ISSUE TITLE
Issue While Using shader file

### ISSUE THREAD

**Issue by shashankKayo** [twostraws/ShaderKit#3]
Jet: Error Domain=MTLLibraryErrorDomain Code=3 "Compilation failed: 

program_source:33:1: error: unknown type name 'SHKWater'
SHKWater
^
program_source:33:9: error: expected unqualified-id
SHKWater
        ^
" UserInfo={NSLocalizedDescription=Compilation failed: 

program_source:33:1: error: unknown type name 'SHKWater'
SHKWater
^
program_source:33:9: error: expected unqualified-id
SHKWater
        ^
}
2020-01-20 15:30:49.461672+0530 paperboat[7746:150969] SKShader failed to compile:
Compilation failed: 

program_source:33:1: error: unknown type name 'SHKWater'
SHKWater
^
program_source:33:9: error: expected unqualified-id
SHKWater
        ^

**Comment by twostraws** [comment]
This error means you're compiling Swift code as a shader, which won't work.
