### ISSUE TITLE
Including this code in other projects

### ISSUE THREAD

**Issue by ShinryakuTako** [twostraws/ShaderKit#4]
Thanks for these! I mean to use some of this code in my own open-source [game engine](https://github.com/InvadingOctopus/octopuskit).

Do I need to do anything besides including the full header and license in each relevant file?

Will I have to modify my own license (the default Apache-2.0)?

**Comment by twostraws** [comment]
Hello! I'm afraid I'm not in a position to provide legal advice on licenses. You should look here or similar: https://law.stackexchange.com/questions/6081/can-i-bundle-mit-licensed-components-in-a-apache-2-0-licensed-project
